spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:33006/javacarwash
    username: root
    password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
---
app:
  token:
    secret: fvpl6gmrgxHoLiu
    issuser: BackendByJava




