spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:33006/testmysqlapi
    username: root
    password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB



